/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace CaseSale {
  export type OpeningStruct = {
    buyer: AddressLike;
    caseTypeId: BigNumberish;
    rewardAmount: BigNumberish;
    reservedAmount: BigNumberish;
    btcUsdPrice: BigNumberish;
    rewarded: boolean;
    claimed: boolean;
  };

  export type OpeningStructOutput = [
    buyer: string,
    caseTypeId: bigint,
    rewardAmount: bigint,
    reservedAmount: bigint,
    btcUsdPrice: bigint,
    rewarded: boolean,
    claimed: boolean
  ] & {
    buyer: string;
    caseTypeId: bigint;
    rewardAmount: bigint;
    reservedAmount: bigint;
    btcUsdPrice: bigint;
    rewarded: boolean;
    claimed: boolean;
  };
}

export interface CaseSaleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "CBBTC_SCALE"
      | "USD_SCALE"
      | "availableCases"
      | "btcUsdDecimals"
      | "btcUsdFeed"
      | "btcUsdScale"
      | "caseTypes"
      | "cbBtc"
      | "claimReward"
      | "getOpening"
      | "maxPriceAge"
      | "nextOpeningId"
      | "openings"
      | "owner"
      | "purchaseCase"
      | "renounceOwnership"
      | "reservedReward"
      | "setCaseType"
      | "setMaxPriceAge"
      | "setTreasury"
      | "transferOwnership"
      | "treasury"
      | "usdc"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CaseClaimed"
      | "CasePurchased"
      | "CaseRewarded"
      | "CaseTypeUpdated"
      | "MaxPriceAgeUpdated"
      | "OwnershipTransferred"
      | "TreasuryUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "CBBTC_SCALE",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "USD_SCALE", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "availableCases",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "btcUsdDecimals",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "btcUsdFeed",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "btcUsdScale",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "caseTypes",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "cbBtc", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "claimReward",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getOpening",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "maxPriceAge",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nextOpeningId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "openings",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "purchaseCase",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reservedReward",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setCaseType",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      boolean
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxPriceAge",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTreasury",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "treasury", values?: undefined): string;
  encodeFunctionData(functionFragment: "usdc", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "CBBTC_SCALE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "USD_SCALE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "availableCases",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "btcUsdDecimals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "btcUsdFeed", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "btcUsdScale",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "caseTypes", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "cbBtc", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getOpening", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "maxPriceAge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextOpeningId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "openings", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "purchaseCase",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reservedReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCaseType",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMaxPriceAge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "usdc", data: BytesLike): Result;
}

export namespace CaseClaimedEvent {
  export type InputTuple = [
    openingId: BigNumberish,
    buyer: AddressLike,
    rewardAmount: BigNumberish
  ];
  export type OutputTuple = [
    openingId: bigint,
    buyer: string,
    rewardAmount: bigint
  ];
  export interface OutputObject {
    openingId: bigint;
    buyer: string;
    rewardAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CasePurchasedEvent {
  export type InputTuple = [
    buyer: AddressLike,
    caseTypeId: BigNumberish,
    openingId: BigNumberish,
    priceUSDC: BigNumberish
  ];
  export type OutputTuple = [
    buyer: string,
    caseTypeId: bigint,
    openingId: bigint,
    priceUSDC: bigint
  ];
  export interface OutputObject {
    buyer: string;
    caseTypeId: bigint;
    openingId: bigint;
    priceUSDC: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CaseRewardedEvent {
  export type InputTuple = [
    openingId: BigNumberish,
    rewardAmount: BigNumberish
  ];
  export type OutputTuple = [openingId: bigint, rewardAmount: bigint];
  export interface OutputObject {
    openingId: bigint;
    rewardAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CaseTypeUpdatedEvent {
  export type InputTuple = [
    caseTypeId: BigNumberish,
    priceUSDC: BigNumberish,
    minRewardUsd: BigNumberish,
    maxRewardUsd: BigNumberish,
    positiveReturnBps: BigNumberish,
    enabled: boolean
  ];
  export type OutputTuple = [
    caseTypeId: bigint,
    priceUSDC: bigint,
    minRewardUsd: bigint,
    maxRewardUsd: bigint,
    positiveReturnBps: bigint,
    enabled: boolean
  ];
  export interface OutputObject {
    caseTypeId: bigint;
    priceUSDC: bigint;
    minRewardUsd: bigint;
    maxRewardUsd: bigint;
    positiveReturnBps: bigint;
    enabled: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MaxPriceAgeUpdatedEvent {
  export type InputTuple = [maxPriceAge: BigNumberish];
  export type OutputTuple = [maxPriceAge: bigint];
  export interface OutputObject {
    maxPriceAge: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TreasuryUpdatedEvent {
  export type InputTuple = [treasury: AddressLike];
  export type OutputTuple = [treasury: string];
  export interface OutputObject {
    treasury: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CaseSale extends BaseContract {
  connect(runner?: ContractRunner | null): CaseSale;
  waitForDeployment(): Promise<this>;

  interface: CaseSaleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  CBBTC_SCALE: TypedContractMethod<[], [bigint], "view">;

  USD_SCALE: TypedContractMethod<[], [bigint], "view">;

  availableCases: TypedContractMethod<
    [caseTypeId: BigNumberish],
    [bigint],
    "view"
  >;

  btcUsdDecimals: TypedContractMethod<[], [bigint], "view">;

  btcUsdFeed: TypedContractMethod<[], [string], "view">;

  btcUsdScale: TypedContractMethod<[], [bigint], "view">;

  caseTypes: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, boolean] & {
        priceUSDC: bigint;
        minRewardUsd: bigint;
        maxRewardUsd: bigint;
        positiveReturnBps: bigint;
        enabled: boolean;
      }
    ],
    "view"
  >;

  cbBtc: TypedContractMethod<[], [string], "view">;

  claimReward: TypedContractMethod<
    [openingId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getOpening: TypedContractMethod<
    [openingId: BigNumberish],
    [CaseSale.OpeningStructOutput],
    "view"
  >;

  maxPriceAge: TypedContractMethod<[], [bigint], "view">;

  nextOpeningId: TypedContractMethod<[], [bigint], "view">;

  openings: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, bigint, bigint, boolean, boolean] & {
        buyer: string;
        caseTypeId: bigint;
        rewardAmount: bigint;
        reservedAmount: bigint;
        btcUsdPrice: bigint;
        rewarded: boolean;
        claimed: boolean;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  purchaseCase: TypedContractMethod<
    [caseTypeId: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  reservedReward: TypedContractMethod<[], [bigint], "view">;

  setCaseType: TypedContractMethod<
    [
      caseTypeId: BigNumberish,
      priceUSDC: BigNumberish,
      minRewardUsd: BigNumberish,
      maxRewardUsd: BigNumberish,
      positiveReturnBps: BigNumberish,
      enabled: boolean
    ],
    [void],
    "nonpayable"
  >;

  setMaxPriceAge: TypedContractMethod<
    [newMaxPriceAge: BigNumberish],
    [void],
    "nonpayable"
  >;

  setTreasury: TypedContractMethod<
    [newTreasury: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  treasury: TypedContractMethod<[], [string], "view">;

  usdc: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "CBBTC_SCALE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "USD_SCALE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "availableCases"
  ): TypedContractMethod<[caseTypeId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "btcUsdDecimals"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "btcUsdFeed"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "btcUsdScale"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "caseTypes"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, boolean] & {
        priceUSDC: bigint;
        minRewardUsd: bigint;
        maxRewardUsd: bigint;
        positiveReturnBps: bigint;
        enabled: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "cbBtc"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "claimReward"
  ): TypedContractMethod<[openingId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getOpening"
  ): TypedContractMethod<
    [openingId: BigNumberish],
    [CaseSale.OpeningStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "maxPriceAge"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "nextOpeningId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "openings"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, bigint, bigint, boolean, boolean] & {
        buyer: string;
        caseTypeId: bigint;
        rewardAmount: bigint;
        reservedAmount: bigint;
        btcUsdPrice: bigint;
        rewarded: boolean;
        claimed: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "purchaseCase"
  ): TypedContractMethod<[caseTypeId: BigNumberish], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "reservedReward"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "setCaseType"
  ): TypedContractMethod<
    [
      caseTypeId: BigNumberish,
      priceUSDC: BigNumberish,
      minRewardUsd: BigNumberish,
      maxRewardUsd: BigNumberish,
      positiveReturnBps: BigNumberish,
      enabled: boolean
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setMaxPriceAge"
  ): TypedContractMethod<[newMaxPriceAge: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTreasury"
  ): TypedContractMethod<[newTreasury: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "treasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "usdc"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "CaseClaimed"
  ): TypedContractEvent<
    CaseClaimedEvent.InputTuple,
    CaseClaimedEvent.OutputTuple,
    CaseClaimedEvent.OutputObject
  >;
  getEvent(
    key: "CasePurchased"
  ): TypedContractEvent<
    CasePurchasedEvent.InputTuple,
    CasePurchasedEvent.OutputTuple,
    CasePurchasedEvent.OutputObject
  >;
  getEvent(
    key: "CaseRewarded"
  ): TypedContractEvent<
    CaseRewardedEvent.InputTuple,
    CaseRewardedEvent.OutputTuple,
    CaseRewardedEvent.OutputObject
  >;
  getEvent(
    key: "CaseTypeUpdated"
  ): TypedContractEvent<
    CaseTypeUpdatedEvent.InputTuple,
    CaseTypeUpdatedEvent.OutputTuple,
    CaseTypeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "MaxPriceAgeUpdated"
  ): TypedContractEvent<
    MaxPriceAgeUpdatedEvent.InputTuple,
    MaxPriceAgeUpdatedEvent.OutputTuple,
    MaxPriceAgeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "TreasuryUpdated"
  ): TypedContractEvent<
    TreasuryUpdatedEvent.InputTuple,
    TreasuryUpdatedEvent.OutputTuple,
    TreasuryUpdatedEvent.OutputObject
  >;

  filters: {
    "CaseClaimed(uint256,address,uint256)": TypedContractEvent<
      CaseClaimedEvent.InputTuple,
      CaseClaimedEvent.OutputTuple,
      CaseClaimedEvent.OutputObject
    >;
    CaseClaimed: TypedContractEvent<
      CaseClaimedEvent.InputTuple,
      CaseClaimedEvent.OutputTuple,
      CaseClaimedEvent.OutputObject
    >;

    "CasePurchased(address,uint256,uint256,uint256)": TypedContractEvent<
      CasePurchasedEvent.InputTuple,
      CasePurchasedEvent.OutputTuple,
      CasePurchasedEvent.OutputObject
    >;
    CasePurchased: TypedContractEvent<
      CasePurchasedEvent.InputTuple,
      CasePurchasedEvent.OutputTuple,
      CasePurchasedEvent.OutputObject
    >;

    "CaseRewarded(uint256,uint256)": TypedContractEvent<
      CaseRewardedEvent.InputTuple,
      CaseRewardedEvent.OutputTuple,
      CaseRewardedEvent.OutputObject
    >;
    CaseRewarded: TypedContractEvent<
      CaseRewardedEvent.InputTuple,
      CaseRewardedEvent.OutputTuple,
      CaseRewardedEvent.OutputObject
    >;

    "CaseTypeUpdated(uint256,uint256,uint256,uint256,uint16,bool)": TypedContractEvent<
      CaseTypeUpdatedEvent.InputTuple,
      CaseTypeUpdatedEvent.OutputTuple,
      CaseTypeUpdatedEvent.OutputObject
    >;
    CaseTypeUpdated: TypedContractEvent<
      CaseTypeUpdatedEvent.InputTuple,
      CaseTypeUpdatedEvent.OutputTuple,
      CaseTypeUpdatedEvent.OutputObject
    >;

    "MaxPriceAgeUpdated(uint256)": TypedContractEvent<
      MaxPriceAgeUpdatedEvent.InputTuple,
      MaxPriceAgeUpdatedEvent.OutputTuple,
      MaxPriceAgeUpdatedEvent.OutputObject
    >;
    MaxPriceAgeUpdated: TypedContractEvent<
      MaxPriceAgeUpdatedEvent.InputTuple,
      MaxPriceAgeUpdatedEvent.OutputTuple,
      MaxPriceAgeUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "TreasuryUpdated(address)": TypedContractEvent<
      TreasuryUpdatedEvent.InputTuple,
      TreasuryUpdatedEvent.OutputTuple,
      TreasuryUpdatedEvent.OutputObject
    >;
    TreasuryUpdated: TypedContractEvent<
      TreasuryUpdatedEvent.InputTuple,
      TreasuryUpdatedEvent.OutputTuple,
      TreasuryUpdatedEvent.OutputObject
    >;
  };
}
