/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { BasedRoomRewards__factory } from "./BasedRoomRewards__factory";
export { IXCaseStaking__factory } from "./IXCaseStaking__factory";
