/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IXCaseStaking,
  IXCaseStakingInterface,
} from "../../../contracts/BasedRoomRewards.sol/IXCaseStaking";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "stakedBalance",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IXCaseStaking__factory {
  static readonly abi = _abi;
  static createInterface(): IXCaseStakingInterface {
    return new Interface(_abi) as IXCaseStakingInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IXCaseStaking {
    return new Contract(address, _abi, runner) as unknown as IXCaseStaking;
  }
}
