/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BasedRoomRewards } from "./BasedRoomRewards";
export type { IXCaseStaking } from "./IXCaseStaking";
